### ISSUE TITLE
Idea : Upgrading PHP and other components to its latest version

### ISSUE THREAD

**Issue by hikmatsp** [romualdr/zwamp-nighty-win64#2]
Thanks for your version of Zwamp, I've been using it for several month. I'm a Xampp refugee. Now a CMS I will using, which is Grav is requiring a minimum PHP 7.1.3.

Thanks in advance

Btw, here is the https://learn.getgrav.org/16/basics/requirements

**Comment by romualdr** [comment]
Hello. Thank you for your feedback.

Please submit a pull request.

Have a nice day

**Comment by romualdr** [comment]
Hello @hikmatsp 

I finished a new version of the tool. Please go to https://github.com/romualdr/xwamp. I tested with Graw and it works well.

I migrated from ZWAMP (because the ZWAMP is not maintained anymore) and created this new tool - which is basically the same tool but with updated version and in Go.

I will make this repository read-only from now.
